inventaire/urls.py
from django.conf.urls import patterns, url
from djgeojson.views import GeoJSONLayerView
from . import views
from .views import DocListView, DocDetailView, OpMapListView, Operation, Sequence, UniteDetailView, MentionDetailView


app_name = 'inventaire'
urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^document/(?P<slug>[^/]+)', views.DocDetailView.as_view(), name='docDetail'),
    url(r'^document/$', views.DocListView.as_view(), name='docIndex'),
    url(r'^operation/data.geojson', GeoJSONLayerView.as_view(model=Operation, properties=('popupContent',)), name='opData'),
    url(r'^operation/$', views.OpMapListView.as_view(), name='opMapIndex'),
    url(r'^operation/(?P<slug>[^/]+)', views.OpMapDetailView.as_view(), name='opMapDetail'),
    url(r'^sequence/$', views.SequenceListView.as_view(), name='sequenceIndex'),
    url(r'^sequence/(?P<pk>[^/]+)', views.SequenceDetailView.as_view(), name='sequenceDetail'),
    url(r'^mention/(?P<pk>[^/]+)', views.MentionDetailView.as_view(), name='mentionDetail'),
    url(r'^unite/(?P<pk>[^/]+)', views.UniteDetailView.as_view(), name='uniteDetail'),
   # url(r'^unite/$', views.unite, name='unite_table'),
)

quorel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.gis import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('inventaire.urls', namespace="inventaire")),
]

inventaire/models.py
from __future__ import unicode_literals
import uuid

from django.db import models
from django.core.validators import MaxValueValidator
from django.utils.encoding import python_2_unicode_compatible
from django.core.urlresolvers import reverse
import django_tables2 as tables
#import mptt
# import GIS
from django.contrib.gis.db import models as gismodels



# Create your models here.
@python_2_unicode_compatible
class Document(models.Model):
    nom_document = models.CharField(max_length=100)
    auteur = models.CharField(max_length=100)
    annee = models.PositiveIntegerField(validators=[MaxValueValidator(2016)])
    commentaire = models.TextField(blank=True, null=True)
    traitement = models.BooleanField()
    slug = models.SlugField(u'slug',blank=False, default='',help_text='indiquer un nom unique pour url', max_length=64)

    #@permalink
    def get_absolute_url(self):
        return reverse('docDetail', args=[self.pk])

    def __str__(self):
    	return self.nom_document

# try:
#     mptt.register(Document)
# except mptt.AlreadyRegistered:
#     pass

@python_2_unicode_compatible
class Unite(models.Model):
    nom_unite = models.CharField(max_length=100)
    profondeur = models.FloatField(default=0.00)
    epaisseur = models.FloatField(default=0.00)
    texture_choix =  (
    ('aucune','aucune'),
    ('caillouteux','caillouteux'),
    ('graveleux','graveleux'),
    ('sableux','sableux'),
    ('limoneux','limoneux'),
    ('argileux','argileux')
    )
    texture_1 = models.CharField(max_length=50,
        choices=texture_choix,
        default='indéfini'
        )
    texture_2 = models.CharField(max_length=50,
        choices=texture_choix,
        default='indéfini'
        )
    couleur_choix =  (
    ('aucune','aucune'),
    ('blanc','blanc'),
    ('gris','gris'),
    ('noir','noir'),
    ('brun','brun'),
    ('jaune','jaune'),
    ('orange','orange'),
    ('rouge','rouge'),
    ('vert','vert'),
    ('bleu','bleu'),
    ('rouille','rouille')
    )
    couleur = models.CharField(max_length=50,
        choices=couleur_choix,
        default='indéfini'
        )
    nuance_couleur = models.CharField(max_length=50,
        choices=couleur_choix,
        default='indéfini'
        )
    valeur_choix = (
    ('très sombre','très sombre'),
    ('sombre', 'sombre'),
    ('aucune','aucune'),
    ('clair','clair'),
    ('très clair','très clair')
    )
    valeur_couleur = models.CharField(max_length=50,
        choices=valeur_choix,
        default='aucune'
        )
    couleur_MSCC = models.CharField(max_length=100)
    tache = models.TextField(blank=True, null=True)
    carbonate = models.BooleanField()
    type_carbon_choix =(
        ('masse fine','masse fine'),
        ('secondaire','secondaire'),
        ('poupées','poupées'),
        ('pseudo-mycélium','pseudo-mycélium'),
        ('aucune','aucune')
    )
    type_carbon = models.CharField(max_length=50,
        choices=type_carbon_choix,
        default='indéfini'
        )
    structure_choix =  (
    ('massive','massive'),
    ('lamellaire','lamellaire'),
    ('polyédrique','polyédrique'),
    ('prismatique','prismatique'),
    ('grumeleuse','grumeleuse'),
    ('grenue','grenue')
    )
    structure_1 = models.CharField(max_length=50,
        choices=structure_choix,
        default='indéfini'
        )
    taille_structure_choix = (
        ('très fine', 'très fine'),
        ('fine', 'fine'),
        ('pas de taille particulière','pas de taille particulière'),
        ('grossière','grossière'),
        ('très grossière','très grossière')
    )
    taille_structure = models.CharField(max_length=50,
        choices=taille_structure_choix,
        default='pas de taille particulière'
        )
    structure_2 = models.CharField(max_length=50,
        choices=structure_choix,
        default='indéfini'
        )
    sous_structure = models.CharField(max_length=50,
        choices=structure_choix,
        default='indéfini'
        )
    description_structure = models.CharField(blank=True, max_length=100, null=True)
    compacite_choix = (
        ('très compact', 'très compact'),
        ('compact', 'compact'),
        ('peu compact','peu compact'),
        ('meuble','meuble'),
        ('très meuble','très meuble')
    )
    compacite = models.CharField(max_length=50,
        choices=compacite_choix,
        default='indéfini'
        )
    inclusion = models.CharField(blank=True, max_length=100, null=True)
    mobilier = models.TextField(blank=True, null=True)
    perturbation = models.TextField(blank=True, null=True)
    interpretation_sedimentaire = models.CharField(blank=True, max_length=100, null=True)
    interpretation_pedologique = models.CharField(blank=True, max_length=100, null=True)
    interface = models.CharField(max_length=100, null=True)
    echantillon = models.CharField(max_length=100, default='indéfini')
    autre = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nom_unite


@python_2_unicode_compatible
class Sequence(models.Model):
    nom_sequence = models.CharField(unique=True, max_length=50)
    unite = models.ManyToManyField(Unite)

    def __str__(self):
    	return self.nom_sequence

@python_2_unicode_compatible
class Mention(models.Model):
    mention = models.TextField()
    page = models.CharField(max_length=50)
    commentaire = models.TextField(blank=True, null=True)
    document = models.ForeignKey(Document, blank=True, null=True)
    sequence =  models.ManyToManyField(Sequence)

    def __str__(self):
    	return self.mention

@python_2_unicode_compatible
class Operation(models.Model):
    nom_operation = models.CharField(max_length=100)
    type_op_choix =  (
    ('fouille préventive','fouille préventive'),
    ('diagnostic préventif','diagnostic préventif'),
    ('fouille programmée','fouille programmée'),
    ('carrière','carrière'),
    ('autre chantier','autre chantier'),
    ('autre','autre'),
    )
    type_operation = models.CharField(max_length=25,
    	choices=type_op_choix,
    	default='indéfini'
    	)
    geom = gismodels.PointField(null=True, blank=True, dim=3)
    z = models.FloatField(null=True, blank=True)
    slug = models.SlugField(u'slug',blank=False, default='',help_text='indiquer un nom unique pour url', max_length=64)

    def geom_as_text(self):
        return self.geom

    @property
    def popupContent(self):
      return '<a href="'+ self.slug +'">'+ self.nom_operation +'</a>'

    def __str__(self):
    	return self.nom_operation + ' : ' + self.type_operation



@python_2_unicode_compatible  # only if you need to support Python 2
class Sondage(models.Model):
    nom_sondage = models.CharField(max_length=100)
    operation = models.ForeignKey(Operation, blank=True, null=True)

    geom = gismodels.PointField(null=True, blank=True, dim=3)

    def __str__(self):
    	return self.nom_sondage


@python_2_unicode_compatible
class Observation(models.Model):
    nom_observation = models.CharField(max_length=100)
    type_obs_choix = (
    ('log','log'),
    ('coupe','coupe'),
    ('plan','plan'),
    )
    type_observation = models.CharField(max_length=50,
    	choices=type_obs_choix,
    	default='indéfini'
    	)
    sondage = models.ForeignKey(Sondage, blank=True, null=True)
    sequence = models.ForeignKey(Sequence, blank=True, null=True)

    acces_possible = models.BooleanField()


    def __str__(self):
    	return self.nom_observation



class UniteTableFull(tables.Table):
    unite = tables.Column(accessor='nom_unite')
    #title = tables.Column()
    epaisseur = tables.Column(accessor='epaisseur')
    texture_1 = tables.Column(verbose_name="texture_1")
    texture_2 = tables.Column(verbose_name="texture_2")
     
    class Meta:
        model = Unite
        exclude = ()
        attrs = {"class": "paleblue"}

inventaire/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django_tables2   import RequestConfig
from django.utils import timezone
from .models import Document, Mention, Operation, Sequence, Unite, Mention

# Create your views here.
def index(request):
   
    return render(request, 'inventaire/quorelIndex.html')



class DocListView(generic.ListView):
    template_name = 'inventaire/docIndex.html'
    context_object_name = 'latest_document_list'
    queryset = Document.objects.all
    

class DocDetailView(generic.DetailView):
    model = Document
    context_object_name = 'document'
    template_name = 'inventaire/docDetail.html'


class OpMapListView(generic.ListView):
    model = Operation
    template_name = 'inventaire/opMapIndex.html'

class OpMapDetailView(generic.DetailView):
    model = Operation
    template_name = 'inventaire/opMapDetail.html'


class SequenceListView(generic.ListView):
    template_name = 'inventaire/sequenceIndex.html'
    context_object_name = 'sequence_list'
    queryset = Sequence.objects.all

class SequenceDetailView(generic.DetailView):
    model = Sequence
    template_name = 'inventaire/sequenceDetail.html'
    context_object_name = 'sequence_detail'

class UniteDetailView(generic.DetailView):
    model = Unite
    template_name = 'inventaire/uniteDetail.html'
    context_object_name = 'unite_detail'
    
#def unite(request):
#     unite_table = UniteTableFull(Unite.objects.order_by('nom_unite'))
#     RequestConfig(request, paginate=False).configure(unite_table)
     
#     return render(request, 'inventaire/unite_table.html', {'unite_table': unite_table})
class MentionDetailView(generic.DetailView):
    model = Mention
    template_name = 'inventaire/mentionDetail.html'
    context_object_name = 'mention_detail'
    

inventaire/templates/inventaire/docDetail.html
{% extends "base.html" %}

{% block content %}

<div class="">
        <h1>{{ document.nom_document }}</h1>
        {% if document.mention_set.all|length > 1 %}   
        <p>{{ document.mention_set.all|length }} mentions</p>
        {% else %}
        <p>{{ document.mention_set.all|length }} mention</p>
        {% endif %}
        {% if document.auteur %}
        <p>{{ document.auteur }}</p>
        {% endif %}
        {% if document.annee %}
        <p>{{ document.annee }}</p>
        {% endif %}
        {% if document.commentaire %}
        <p>{{ document.comentaire }}</p>
        {% endif %}  
        {% if document.traitement %}
        <p>{{ document.traitement }}</p>
        {% endif %}         


        <ul  class="list-inline" class="thumbnails"> 
                {% for mention in document.mention_set.all %}          
                <li><a href=" ../mention/{{mention.pk}}">{{ mention }}</a></li>
                </li>
                {% endfor %}
        </ul>

</div>
{% endblock content %}

inventaire/templates/inventaire/docIndex.html
{% extends "base.html" %}

{% block content %}

<div class="">
	{% if latest_document_list %}
	    <ul>
	    {% for Document in latest_document_list %}
	    <li><a href="{{ Document.slug }}">{{ Document.nom_document }}</a></li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>Aucun document n'est disponbile.</p>
	{% endif %}
</div>
{% endblock content %}

inventaire/templates/inventaire/mentionDetail.html
{% extends "base.html" %}

{% block content %}




<div class="">
        <h1>{{ mention_detail.mention }}</h1>
        {% if mention_detail.page %}
        <p>Pages : {{ mention_detail.page }}</p>
        {% endif %}
        {% if mention_detail.mention %}
        <p>Mention : {{ mention_detail.mention }}</p>
        {% endif %}
        {% if mention_detail.commentaire %}
        <p>Commentaire : {{ mention_detail.commentaire }}</p>
        {% endif %}
        {% if mention_detail.document %}
        <p>Document : {{ mention_detail.document}}s</p>
        {% endif %}
        {% if mention_detail.sequence.all|length > 1 %}   
        <p>{{ mention_detail.sequence.all|length }} sequences : </p>
        <ul  class="list-inline" class="thumbnails"> 
                {% for sequence in mention_detail.sequence.all %}          
                <li><a href=" ../sequence/{{sequence.pk}}">{{ sequence }}</a></li>
                </li>
                {% endfor %}
          </ul>
        {% else %}
        <p>{{ mention_detail.sequence.all|length }} sequence : </p>
          {% for sequence in mention_detail.sequence.all %}          
                <li><a href=" ../sequence/{{sequence.pk}}">{{ sequence }}</a></li>
                </li>
          {% endfor %}
        {% endif %}   
        
</div>




{% endblock content %}

inventaire/templates/inventaire/opMapDetail.html
{% extends "base.html" %}
{% load leaflet_tags %}
{% load geojson_tags %}
 
{% block content %}

<div class="">
        <h1>{{ operation.nom_operation }}</h1>
        {% if operation.type_operation %}
        <p>Type : {{ operation.type_operation }}</p>
        {% endif %}        
</div>


{% endblock content %}

{% block map %}

    {% leaflet_map "main" callback="main_map_init" %}

    <script type="text/javascript">
    var collection = {{ operation|geojsonfeature|safe }};

    
    function main_map_init(map, options) {
        var layer = L.geoJson(collection);
        var overlaysBounds =[];
        layer.addTo(map);
        overlaysBounds.push(layer.getBounds());
       
        // featureLayer.getBounds() returns the corners of the furthest-out markers,
        // and map.fitBounds() makes sure that the map contains these.
        map.fitBounds(overlaysBounds, {padding: [50, 50]});
        map.setZoom(13);
        
    }
        
    </script>
{% endblock map %}

  

inventaire/templates/inventaire/opMapIndex.html
{% extends "base.html" %}
{% load leaflet_tags %}
{% leaflet_js %}
{% leaflet_css %}

  {% block content %}
    <h1>Opérations</h1>
  {% endblock content %}
    
{% block map %}

    {% leaflet_map "main" callback="main_map_init" %}

    <script type="text/javascript">
        function main_map_init (map, options) {
            // Use Leaflet API here
             var dataurl = '{% url "inventaire:opData" %}';
             // Download GeoJSON via Ajax
             $.getJSON(dataurl, function (data) {
                 // Add GeoJSON layer
                 L.geoJson(data, {onEachFeature: onEachFeature}).addTo(map);
             });
        }

        function onEachFeature(feature, layer) {
          // does this feature have a property named popupContent?
            if (feature.properties && feature.properties.popupContent) {
                  layer.bindPopup(feature.properties.popupContent);
            }
        }
    </script>
{% endblock map %}

  

inventaire/templates/inventaire/quorelIndex.html
{% extends "base.html" %}

{% block content %}

<li><a href="{% url 'inventaire:docIndex' %}">Documents</a></li>
<li><a href="{% url 'inventaire:sequenceIndex' %}">Sequences</a></li>
<li><a href="{% url 'inventaire:opMapIndex' %}">Operations</a></li>

{% endblock content %}

inventaire/templates/inventaire/sequenceDetail.html
{% extends "base.html" %}

{% block content %}




<div class="">
        <h1>{{ sequence_detail.nom_sequence }}</h1>
        {% if sequence_detail.unite.all|length > 1 %}   
        <p>{{ sequence_detail.unite.all|length }} unites</p>
        {% else %}
        <p>{{ sequence_detail.unite.all|length }} unite</p>
        {% endif %}   
</div>

<ul  class="list-inline" class="thumbnails"> 
  		{% for unite in sequence_detail.unite.all %}
  			
  		
      <li><a href=" ../unite/{{unite.pk}}">{{ unite }}</a></li>
      </li>
      {% endfor %}
      </ul>



{% endblock content %}

inventaire/templates/inventaire/sequenceIndex.html
{% extends "base.html" %}

 {% block content %}
<h1>Séquences</h1>
<div class="">
	    {% if sequence_list %}
	    <ul>
	    {% for Sequence in sequence_list %}
	    <li><a href="{{ Sequence.pk }}">{{ Sequence.nom_sequence }}</a></li>
	    {% endfor %}
	    </ul>
		{% else %}
	    <p>Aucune séquence n'est disponbile.</p>
		{% endif %}
</div>



 {% endblock content %}

inventaire/templates/inventaire/uniteDetail.html
{% extends "base.html" %}

{% block content %}




<div class="">
        <h1>{{ unite_detail.nom_unite }}</h1>

        {% if unite_detail.profondeur %}
        <p>Profondeur : {{ unite_detail.profondeur }}</p>
        {% endif %}
        {% if unite_detail.epaisseur %}
        <p>Epaisseur : {{ unite_detail.epaisseur }}</p>
        {% endif %}
        {% if unite_detail.commentaire %}
        <p>Commentaire : {{ unite_detail.comentaire }}</p>
        {% endif %}  
        {% if unite_detail.texture_1 %}
        <p>Texture 1 : {{ unite_detail.texture_1 }}</p>
        {% endif %}    
        {% if unite_detail.texture_2 %}
        <p>Texture 2 : {{ unite_detail.texture_2 }}</p>
        {% endif %}
        {% if unite_detail.couleur %}
        <p>Couleur : {{ unite_detail.couleur }}</p>
        {% endif %}
        {% if unite_detail.nuance_couleur %}
        <p>Nuance couleur : {{ unite_detail.nuance_couleur }}</p>
        {% endif %}
        {% if unite_detail.valeur_couleur %}
        <p>Valeur couleur : {{ unite_detail.valeur_couleur }}</p>
        {% endif %}
        {% if unite_detail.couleur_MSCC %}
        <p>Code couleur Mansell : {{ unite_detail.couleur_MSCC }}</p>
        {% endif %}
        {% if unite_detail.tache %}
        <p>Tache : {{ unite_detail.tache }}</p>
        {% endif %}
        {% if unite_detail.carbonate %}
        <p>Carbonate : {{ unite_detail.carbonate }}</p>
        {% endif %}
        {% if unite_detail.type_carbon %}
        <p>Type carbon : {{ unite_detail.type_carbon }}</p>
        {% endif %}
        {% if unite_detail.structure_1 %}
        <p>Structure 1 : {{ unite_detail.structure_1 }}</p>
        {% endif %}
        {% if unite_detail.taille_structure %}
        <p>Taille structure : {{ unite_detail.taille_structure }}</p>
        {% endif %}
        {% if unite_detail.structure_2 %}
        <p>Structure 2 : {{ unite_detail.structure_2 }}</p>
        {% endif %}
        {% if unite_detail.sous_structure %}
        <p>Sous structure : {{ unite_detail.sous_structure }}</p>
        {% endif %}
        {% if unite_detail.description_structure %}
        <p>Descritption structure : {{ unite_detail.description_structure }}</p>
        {% endif %}
        {% if unite_detail.compacite %}
        <p>Compacite : {{ unite_detail.compacite }}</p>
        {% endif %}
        {% if unite_detail.inclusion %}
        <p>Inclusion : {{ unite_detail.inclusion }}</p>
        {% endif %}
        {% if unite_detail.mobilier %}
        <p>Mobilier : {{ unite_detail.mobilier }}</p>
        {% endif %}
        {% if unite_detail.perturbation %}
        <p>Perturbation : {{ unite_detail.perturbation }}</p>
        {% endif %}
        {% if unite_detail.interpretation_sedimentaire %}
        <p>Interpretation sedimentaire : {{ unite_detail.interpretation_sedimentaire }}</p>
        {% endif %}
        {% if unite_detail.interpretation_pedologique %}
        <p>Interprétation pédologique : {{ unite_detail.interpretation_pedologique }}</p>
        {% endif %}
        {% if unite_detail.interface %}
        <p>Interface : {{ unite_detail.interface }}</p>
        {% endif %}        
        {% if unite_detail.echantillon %}
        <p>Echantillon : {{ unite_detail.echantillon }}</p>
        {% endif %}
        {% if unite_detail.autre %}
        <p>Autre : {{ unite_detail.autre }}</p>
        {% endif %}



</div>




{% endblock content %}

inventaire/templates/inventaire/unite_table.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block content %}

<div class="fluid-container">
	<div class="row">
	{% render_table unite_table %}

	</div>
</div>


{% endblock content %}